# Generated by Django 4.2.7 on 2023-12-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('not_working', 'Не работает'), ('in_transit', 'В пути'), ('at_airport', 'В аэропорту'), ('picked_up', 'Забрал клиента')], default='not_working', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.driver')),
            ],
        ),
    ]
