# Generated by Django 4.2.7 on 2023-12-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flight_number',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
