# Generated by Django 4.2.7 on 2023-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_passenger_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='arrival_time',
            field=models.CharField(max_length=40),
        ),
    ]
